name: triaxis.com
favicon: null
layout_spectrum: 0.51326
typography_spectrum: 0.13014
title: 'Storing, Managing & Protecting Your Digital Assets'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#224058'
    - '#e4e1d0'
    - '#c4bcb9'
    - '#8b9da7'
    - '#4b6a7f'
  brandStrength: 0.8063353902449568
  lightness: 0.5813908636037223
  saturation: 0.3899660288521033
  rhythmicContrast: 0.13052652669413667
purpose:
  - name: null
    item: null
    url: null
